---
spring:
  application:
    name: hashicorp-vault-poc

server:
  port: 8080

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

---
spring:
  config:
    activate:
      onProfile: staging
  datasource:
    url: jdbc:h2:mem:hashicorp-vault-poc;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;
    driverClassName: org.h2.Driver
    username: ${dbusername}
    password: ${dbpassword}
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        webAllowOthers: true

authentication:
  validApiKeys:
    - ${apikey}

log:
  json: true

---
spring:
  config:
    activate:
      onProfile: production
  datasource:
    url: jdbc:h2:mem:hashicorp-vault-poc;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;
    driverClassName: org.h2.Driver
    username: ${dbusername}
    password: ${dbpassword}
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        webAllowOthers: true

authentication:
  validApiKeys:
    - ${apikey}

log:
  json: true
