apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hashicorp-vault-poc.fullname" . }}
  labels:
    {{- include "hashicorp-vault-poc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hashicorp-vault-poc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "hashicorp-vault-poc.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hashicorp-vault-poc.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            {{- if .Values.debug }}
            - name: debug
              containerPort: 5005
              protocol: TCP
            {{- end }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            {{- if .Values.debug }}
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=80.0 -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            {{- else }}
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=80.0"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: application-config
              mountPath: /app/config/application.yml
              subPath: application.yml
            - name: application-config
              mountPath: /app/config/bootstrap.yml
              subPath: bootstrap.yml
      volumes:
        - name: application-config
          secret:
            secretName: {{ include "hashicorp-vault-poc.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
