apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hashicorp-vault-poc.fullname" . }}
  labels:
    {{- include "hashicorp-vault-poc.labels" . | nindent 4 }}
type: Opaque
stringData:
  application.yml: |
    spring:
      profiles:
        active: {{ required "spring.profiles.active is required" .Values.spring.profiles.active }}
  bootstrap.yml: |
    spring:
      profiles:
        active: {{ required "spring.profiles.active is required" .Values.spring.profiles.active }}

