apiVersion: v1
kind: Service
metadata:
  name: {{ include "hashicorp-vault-poc.fullname" . }}
  labels:
    {{- include "hashicorp-vault-poc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "hashicorp-vault-poc.selectorLabels" . | nindent 4 }}
